
~
8grvy:org.codenarc.rule.basic.AssignmentInConditionalRuleB
grvy3org.codenarc.rule.basic.AssignmentInConditionalRuleMAJOR
|
7grvy:org.codenarc.rule.basic.DuplicateCaseStatementRuleA
grvy2org.codenarc.rule.basic.DuplicateCaseStatementRuleMINOR
ç
0grvy:org.codenarc.rule.basic.EmptyCatchBlockRuleY
grvy+org.codenarc.rule.basic.EmptyCatchBlockRuleMINOR"
ignoreRegexignore|ignored
d
+grvy:org.codenarc.rule.basic.EmptyClassRule5
grvy&org.codenarc.rule.basic.EmptyClassRuleMINOR
l
/grvy:org.codenarc.rule.basic.EmptyElseBlockRule9
grvy*org.codenarc.rule.basic.EmptyElseBlockRuleMINOR
r
2grvy:org.codenarc.rule.basic.EmptyFinallyBlockRule<
grvy-org.codenarc.rule.basic.EmptyFinallyBlockRuleMINOR
r
2grvy:org.codenarc.rule.basic.EmptyForStatementRule<
grvy-org.codenarc.rule.basic.EmptyForStatementRuleMINOR
p
1grvy:org.codenarc.rule.basic.EmptyIfStatementRule;
grvy,org.codenarc.rule.basic.EmptyIfStatementRuleMINOR
Ä
9grvy:org.codenarc.rule.basic.EmptyInstanceInitializerRuleC
grvy4org.codenarc.rule.basic.EmptyInstanceInitializerRuleMINOR
f
,grvy:org.codenarc.rule.basic.EmptyMethodRule6
grvy'org.codenarc.rule.basic.EmptyMethodRuleMINOR
|
7grvy:org.codenarc.rule.basic.EmptyStaticInitializerRuleA
grvy2org.codenarc.rule.basic.EmptyStaticInitializerRuleMINOR
x
5grvy:org.codenarc.rule.basic.EmptySwitchStatementRule?
grvy0org.codenarc.rule.basic.EmptySwitchStatementRuleMINOR
Ñ
;grvy:org.codenarc.rule.basic.EmptySynchronizedStatementRuleE
grvy6org.codenarc.rule.basic.EmptySynchronizedStatementRuleMINOR
j
.grvy:org.codenarc.rule.basic.EmptyTryBlockRule8
grvy)org.codenarc.rule.basic.EmptyTryBlockRuleMINOR
v
4grvy:org.codenarc.rule.basic.EmptyWhileStatementRule>
grvy/org.codenarc.rule.basic.EmptyWhileStatementRuleMINOR
r
2grvy:org.codenarc.rule.basic.EqualsAndHashCodeRule<
grvy-org.codenarc.rule.basic.EqualsAndHashCodeRuleMINOR
p
1grvy:org.codenarc.rule.basic.EqualsOverloadedRule;
grvy,org.codenarc.rule.basic.EqualsOverloadedRuleMINOR
|
7grvy:org.codenarc.rule.basic.ReturnFromFinallyBlockRuleA
grvy2org.codenarc.rule.basic.ReturnFromFinallyBlockRuleMAJOR
å
?grvy:org.codenarc.rule.basic.ThrowExceptionFromFinallyBlockRuleI
grvy:org.codenarc.rule.basic.ThrowExceptionFromFinallyBlockRuleMAJOR
í
1grvy:org.codenarc.rule.braces.ElseBlockBracesRule]
grvy,org.codenarc.rule.braces.ElseBlockBracesRuleMINOR" 
bracesRequiredForElseIffalse
â
<grvy:org.codenarc.rule.concurrency.NestedSynchronizationRuleI
grvy7org.codenarc.rule.concurrency.NestedSynchronizationRuleCRITICAL
Ä
9grvy:org.codenarc.rule.concurrency.SynchronizedMethodRuleC
grvy4org.codenarc.rule.concurrency.SynchronizedMethodRuleMAJOR
é
@grvy:org.codenarc.rule.concurrency.SystemRunFinalizersOnExitRuleJ
grvy;org.codenarc.rule.concurrency.SystemRunFinalizersOnExitRuleMAJOR
u
2grvy:org.codenarc.rule.concurrency.ThreadYieldRule?
grvy-org.codenarc.rule.concurrency.ThreadYieldRuleCRITICAL
é
@grvy:org.codenarc.rule.concurrency.VolatileLongOrDoubleFieldRuleJ
grvy;org.codenarc.rule.concurrency.VolatileLongOrDoubleFieldRuleMAJOR
z
6grvy:org.codenarc.rule.convention.ConfusingTernaryRule@
grvy1org.codenarc.rule.convention.ConfusingTernaryRuleMAJOR
Ä
9grvy:org.codenarc.rule.convention.HashtableIsObsoleteRuleC
grvy4org.codenarc.rule.convention.HashtableIsObsoleteRuleMINOR
v
4grvy:org.codenarc.rule.convention.InvertedIfElseRule>
grvy/org.codenarc.rule.convention.InvertedIfElseRuleMAJOR
z
6grvy:org.codenarc.rule.convention.VectorIsObsoleteRule@
grvy1org.codenarc.rule.convention.VectorIsObsoleteRuleMINOR
|
7grvy:org.codenarc.rule.design.CloneableWithoutCloneRuleA
grvy2org.codenarc.rule.design.CloneableWithoutCloneRuleMINOR
n
0grvy:org.codenarc.rule.exceptions.CatchErrorRule:
grvy+org.codenarc.rule.exceptions.CatchErrorRuleMAJOR
v
4grvy:org.codenarc.rule.exceptions.CatchExceptionRule>
grvy/org.codenarc.rule.exceptions.CatchExceptionRuleMAJOR
è
?grvy:org.codenarc.rule.exceptions.CatchNullPointerExceptionRuleL
grvy:org.codenarc.rule.exceptions.CatchNullPointerExceptionRuleCRITICAL
á
;grvy:org.codenarc.rule.exceptions.CatchRuntimeExceptionRuleH
grvy6org.codenarc.rule.exceptions.CatchRuntimeExceptionRuleCRITICAL
n
0grvy:org.codenarc.rule.exceptions.ThrowErrorRule:
grvy+org.codenarc.rule.exceptions.ThrowErrorRuleMAJOR
v
4grvy:org.codenarc.rule.exceptions.ThrowExceptionRule>
grvy/org.codenarc.rule.exceptions.ThrowExceptionRuleMAJOR
å
?grvy:org.codenarc.rule.exceptions.ThrowNullPointerExceptionRuleI
grvy:org.codenarc.rule.exceptions.ThrowNullPointerExceptionRuleMAJOR
Ñ
;grvy:org.codenarc.rule.exceptions.ThrowRuntimeExceptionRuleE
grvy6org.codenarc.rule.exceptions.ThrowRuntimeExceptionRuleMAJOR
v
4grvy:org.codenarc.rule.exceptions.ThrowThrowableRule>
grvy/org.codenarc.rule.exceptions.ThrowThrowableRuleMAJOR
ñ
Dgrvy:org.codenarc.rule.grails.GrailsPublicControllerMethodRule.fixedN
grvy?org.codenarc.rule.grails.GrailsPublicControllerMethodRule.fixedMINOR
å
?grvy:org.codenarc.rule.grails.GrailsServletContextReferenceRuleI
grvy:org.codenarc.rule.grails.GrailsServletContextReferenceRuleMINOR
~
8grvy:org.codenarc.rule.grails.GrailsSessionReferenceRuleB
grvy3org.codenarc.rule.grails.GrailsSessionReferenceRuleMAJOR
Ã
8grvy:org.codenarc.rule.grails.GrailsStatelessServiceRuleè
grvy3org.codenarc.rule.grails.GrailsStatelessServiceRuleMAJOR"K
ignoreFieldNames7dataSource,scope,sessionFactory, transactional,*Service
r
2grvy:org.codenarc.rule.imports.DuplicateImportRule<
grvy-org.codenarc.rule.imports.DuplicateImportRuleMAJOR
~
8grvy:org.codenarc.rule.imports.ImportFromSamePackageRuleB
grvy3org.codenarc.rule.imports.ImportFromSamePackageRuleMAJOR
~
8grvy:org.codenarc.rule.imports.ImportFromSunPackagesRuleB
grvy3org.codenarc.rule.imports.ImportFromSunPackagesRuleMINOR
Ç
:grvy:org.codenarc.rule.imports.UnnecessaryGroovyImportRuleD
grvy5org.codenarc.rule.imports.UnnecessaryGroovyImportRuleMAJOR
l
/grvy:org.codenarc.rule.imports.UnusedImportRule9
grvy*org.codenarc.rule.imports.UnusedImportRuleMAJOR
b
*grvy:org.codenarc.rule.logging.PrintlnRule4
grvy%org.codenarc.rule.logging.PrintlnRuleMINOR
r
2grvy:org.codenarc.rule.logging.PrintStackTraceRule<
grvy-org.codenarc.rule.logging.PrintStackTraceRuleMAJOR
p
1grvy:org.codenarc.rule.logging.SystemErrPrintRule;
grvy,org.codenarc.rule.logging.SystemErrPrintRuleMAJOR
o
1grvy:org.codenarc.rule.logging.SystemOutPrintRule:
grvy,org.codenarc.rule.logging.SystemOutPrintRuleINFO
Ä
9grvy:org.codenarc.rule.naming.ClassNameSameAsFilenameRuleC
grvy4org.codenarc.rule.naming.ClassNameSameAsFilenameRuleMINOR
¶
0grvy:org.codenarc.rule.size.NestedBlockDepthRuler
grvy+org.codenarc.rule.size.NestedBlockDepthRuleMAJOR"
maxNestedBlockDepth5"
ignoreRegex.*(b|B)uilder
|
7grvy:org.codenarc.rule.unused.UnusedMethodParameterRuleA
grvy2org.codenarc.rule.unused.UnusedMethodParameterRuleMINOR
ú
4grvy:org.codenarc.rule.unused.UnusedPrivateFieldRuled
grvy/org.codenarc.rule.unused.UnusedPrivateFieldRuleMAJOR"$
ignoreFieldNamesserialVersionUID
ä
>grvy:org.codenarc.rule.unused.UnusedPrivateMethodParameterRuleH
grvy9org.codenarc.rule.unused.UnusedPrivateMethodParameterRuleMINOR
x
5grvy:org.codenarc.rule.unused.UnusedPrivateMethodRule?
grvy0org.codenarc.rule.unused.UnusedPrivateMethodRuleMAJOR
z
6grvy:org.codenarc.rule.unused.UnusedVariableRule.fixed@
grvy1org.codenarc.rule.unused.UnusedVariableRule.fixedMAJOR