
L
vbnet:ArrayDesignatorOnVariable)
vbnetArrayDesignatorOnVariableMAJOR
x
!vbnet:BooleanExpressionComplexityS
vbnetBooleanExpressionComplexityMAJOR"&
!maximumBooleanComplexityThreshold3
M
vbnet:ClassCoupling6
vbnetClassCouplingMAJOR"
couplingThreshold20
@
vbnet:ConcatenationInLoop#
vbnetConcatenationInLoopMAJOR
0
vbnet:DoLoopUsage
vbnetDoLoopUsageMAJOR
D
vbnet:EnumNameHasEnumSuffix%
vbnetEnumNameHasEnumSuffixMAJOR
F
vbnet:EnumNameHasFlagsSuffix&
vbnetEnumNameHasFlagsSuffixMAJOR
h
-vbnet:EventNameHasBeforeOrAfterSuffixOrPrefix7
vbnet'EventNameHasBeforeOrAfterSuffixOrPrefixMAJOR
J
vbnet:ExitSelectRedundantUsage(
vbnetExitSelectRedundantUsageMAJOR
>
vbnet:ExitStatementUsage"
vbnetExitStatementUsageMAJOR
I
vbnet:FileLoc8
vbnetFileLocMAJOR"
maximumFileLocThreshold1000
S
!vbnet:FlagsEnumWithoutInitializer.
vbnetFlagsEnumWithoutInitializerCRITICAL
R
"vbnet:FlagsEnumZeroMemberNamedNone,
vbnetFlagsEnumZeroMemberNamedNoneMAJOR
R
"vbnet:ImmediateArrayInitialization,
vbnetImmediateArrayInitializationMAJOR
@
vbnet:IndexedPropertyName#
vbnetIndexedPropertyNameMAJOR
d
+vbnet:IndexedPropertyWithMultipleParameters5
vbnet%IndexedPropertyWithMultipleParametersMAJOR
R
"vbnet:LongArrayCreationSyntaxUsage,
vbnetLongArrayCreationSyntaxUsageMAJOR
N
vbnet:NestedIfDepth7
vbnetNestedIfDepthMINOR"
maximumNestingLevel3
.
vbnet:NotIsUsage
vbnet
NotIsUsageMAJOR
D
vbnet:OneDeclarationPerLine%
vbnetOneDeclarationPerLineMAJOR
:
vbnet:OnErrorStatement 
vbnetOnErrorStatementMAJOR
@
vbnet:OneStatementPerLine#
vbnetOneStatementPerLineMAJOR
:
vbnet:OptionalArgument 
vbnetOptionalArgumentMAJOR
@
vbnet:ParameterAssignedTo#
vbnetParameterAssignedToMAJOR
F
vbnet:PropertyReturningArray&
vbnetPropertyReturningArrayMAJOR
v
4vbnet:PublicMethodWithMultidimensionalArrayParameter>
vbnet.PublicMethodWithMultidimensionalArrayParameterMAJOR
<
vbnet:ReservedParameter!
vbnetReservedParameterMAJOR
D
vbnet:SelectWithoutCaseElse%
vbnetSelectWithoutCaseElseMAJOR
z
vbnet:SubAndFunctionComplexityX
vbnetSubAndFunctionComplexityMAJOR".
(maximumSubAndFunctionComplexityThreshold10
H
vbnet:ThrowFromPropertyGetter'
vbnetThrowFromPropertyGetterMAJOR
]
vbnet:TrailingCommentD
vbnetTrailingCommentMINOR"#
legalCommentPattern'\s*+[^\s]++
4
vbnet:UnsignedUsage
vbnetUnsignedUsageMAJOR
X
vbnet:WithUsageCandidate<
vbnetWithUsageCandidateMINOR"
minimumSeriesLength6
<
vbnet:WriteOnlyProperty!
vbnetWriteOnlyPropertyMAJOR